# Generated by Django 2.1.7 on 2019-05-24 05:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Wishlist',
        ),
    ]
