# Generated by Django 2.1.7 on 2019-06-14 04:33

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20190614_0431'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupons',
            name='valid_till',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 14, 4, 33, 14, 518686)),
        ),
        migrations.AlterField(
            model_name='productsubcategory',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.ProductCategory'),
        ),
    ]
