# Generated by Django 2.2.10 on 2020-02-19 12:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20190614_0433'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupons',
            name='valid_till',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 20, 12, 41, 2, 308212)),
        ),
    ]
